docs/npwd/Roadmap.md
docs/npwd/dev/BasicDevelopment.md
docs/npwd/dev/DevelopmentBootstrap.md
docs/npwd/dev/FrameworkIntegration.md
docs/npwd/faq.md
docs/npwd/framework/esx.md
docs/npwd/start/Config.md
docs/npwd/start/Install.md
docs/npwd/start/Intro.md

Just a Small Typo fix

---

docs/npwd/configuration/default.md
docs/npwd/configuration/main.md
sidebars.js

Added documentation regarding the general configuration file.

feat(extendable-config): extended docs with configuration file info

---

docs/npwd/faq.md

FAQ is the more common used label for Frequently Asked Questions and perhaps more people would find it.

fix(sidebar-label): update sidebar label for FAQ

---

docs/_export-component-ts.mdx
docs/pefcl/Configuration.md
docs/pefcl/Installation.md
docs/pefcl/developers/Introduction.md
docs/pefcl/developers/api/Client.mdx
docs/pefcl/developers/api/Server.mdx
sidebars.js

Initial docs for PEFCL.
**Actions left**:

feature(pefcl): docs for pefcl

---

docs/npwd/api/server-exports.mdx

Awaiting https://github.com/project-error/npwd/pull/773

docs(callhook): adds docs for onCall export

---

docs/npwd/start/Install.md

feat(docs/npwd): update camera installation for pe-image

---

docs/npwd/start/Install.md

Bring Imgur docs back *Being a gooder citizen*

---

docs/_export-component-ts.mdx
docs/pefcl/developers/FrameworkIntegration.md
docs/pefcl/developers/api/Server.mdx
sidebars.js

feat: more exports documentation & framework integration docs

---

docs/npwd/start/Install.md

make it simpler and less rude than 'go search what u need to change urself Loser' i guess 🤔

Clarify camera's config step

---

docs/pefcl/developers/api/Server.mdx

As the example wasn't full and the arguments list was displayed twice, I thought I could help because I've lost so many hours of my life trying to get it work :D

Update and fix some incomplete exports

---

docs/npwd/start/Install.md

Links are broken, hopefully this fixes it.
No, I can't "run" the wiki.

Fix framework links

---

docs/pefcl/developers/api/Client.mdx

**Wrong client export names**
_giveCash should of been giveNearestPlayerCash and
createInvoice should of been createInvoiceForNearestPlayer._

Wrong client export names

---

docs/pefcl/developers/api/Server.mdx

Updated accountId to receiverAccountIdentifier

---

docs/pefcl/developers/FrameworkIntegration.md
docs/pefcl/developers/api/Server.mdx

feat: added docs for framework integration & added events

---

docs/pefcl/developers/api/Server.mdx

fix: updated all lua examples with OBJECT, not table

---

docs/npwd/faq.md

It seems hard to understand so here an explaination...

How to add external apps to NPWD

---

docusaurus.config.js
package.json
yarn.lock

Bumps deps to latest available.

chore(deps): bump docusaurus deps to latest available

---

docs/npwd/start/Install.md

I just fixed a spelling mistake

small documentation fix

---

docs/npwd/framework/esx.md

Changes to be committed:
modified:   docs/npwd/framework/esx.md
Updated the ESX Integration to work with the new versions from npwd v1.7.4 - v1.5.5

 Updated the ESX Integration documentation.

---

docs/npwd/configuration/main.md

_Added documentation for recently *revived* default contacts configuration option._

docs(configuration): default contacts
